import { IoTDevice } from '@/types/iotCloud';

export function generateArduinoSketch(
  device: IoTDevice,
  serverOrigin = 'https://resursee.vercel.app'
): string {
  const token = device.deviceToken;
  const endpoint = `${serverOrigin}/api/iot/ingest`;

  return `/*
 * =========================================================================
 *  Resursee IoT Cloud · ESP32 Firmware Sketch
 *  Device: ${device.name} (${device.id})
 *  Generated by Resursee IoT Cloud Platform
 * =========================================================================
 * 
 * INSTRUCTIONS:
 * 1. Open this sketch in the Arduino IDE.
 * 2. In Tools -> Board, select "ESP32 Dev Module" (or your specific ESP32 board).
 * 3. Replace YOUR_WIFI_SSID and YOUR_WIFI_PASSWORD with your WiFi details.
 * 4. Connect DHT22/DHT11 sensor to GPIO 4 (optional) and Relay to GPIO 2.
 * 5. Click Upload!
 */

#include <WiFi.h>
#include <HTTPClient.h>
#include <ArduinoJson.h> // Library: ArduinoJson by Benoit Blanchon

// 1. --- WiFi Configuration ---
const char* WIFI_SSID     = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// 2. --- Resursee Cloud Credentials ---
const char* INGEST_URL   = "${endpoint}";
const char* DEVICE_TOKEN = "${token}";

// 3. --- Hardware Pin Assignments ---
const int RELAY_PIN_PUMP  = 2;  // Built-in LED or Relay Switch (Actuator)
const int SENSOR_PIN_DHT  = 4;  // Optional DHT22 / Temperature Sensor pin
const int SENSOR_PIN_SOIL = 34; // Analog Soil Moisture probe (ADC1)

// Telemetry Interval (milliseconds)
const unsigned long SEND_INTERVAL_MS = 3000; // 3 seconds
unsigned long lastSendTime = 0;

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println();
  Serial.println("=========================================");
  Serial.println("   Resursee IoT Cloud · Initializing...  ");
  Serial.println("   Device: ${device.name}                ");
  Serial.println("=========================================");

  // Setup Actuator Pin
  pinMode(RELAY_PIN_PUMP, OUTPUT);
  digitalWrite(RELAY_PIN_PUMP, LOW);

  // Connect to WiFi
  connectWiFi();
}

void loop() {
  // Reconnect WiFi if lost
  if (WiFi.status() != WL_CONNECTED) {
    connectWiFi();
  }

  // Periodic Telemetry Pulse
  unsigned long now = millis();
  if (now - lastSendTime >= SEND_INTERVAL_MS) {
    lastSendTime = now;
    sendTelemetryAndSyncActuators();
  }
}

void connectWiFi() {
  Serial.printf("Connecting to WiFi: %s", WIFI_SSID);
  WiFi.mode(WIFI_STA);
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);

  int retries = 0;
  while (WiFi.status() != WL_CONNECTED && retries < 20) {
    delay(500);
    Serial.print(".");
    retries++;
  }

  if (WiFi.status() == WL_CONNECTED) {
    Serial.println();
    Serial.printf("WiFi Connected! IP Address: %s\\n", WiFi.localIP().toString().c_str());
    Serial.printf("Signal Strength (RSSI): %d dBm\\n", WiFi.RSSI());
  } else {
    Serial.println();
    Serial.println("WiFi connection failed. Retrying next cycle...");
  }
}

void sendTelemetryAndSyncActuators() {
  if (WiFi.status() != WL_CONNECTED) return;

  HTTPClient http;
  http.begin(INGEST_URL);
  http.addHeader("Content-Type", "application/json");
  http.addHeader("x-device-token", DEVICE_TOKEN);

  // 1. Read Physical / Simulated Sensor Values
  // Replace these simulated reads with your actual sensor libraries (e.g. dht.readTemperature()):
  float simulatedTemp = 24.5 + ((random(-15, 15)) / 10.0);
  float simulatedHumidity = 62.0 + ((random(-20, 20)) / 10.0);
  int simulatedLight = random(400, 850);
  int simulatedSoil = random(45, 80);
  int rssi = WiFi.RSSI();

  // 2. Build JSON Telemetry Payload
  StaticJsonDocument<384> doc;
  doc["deviceToken"]   = DEVICE_TOKEN;
  doc["temperature"]   = simulatedTemp;
  doc["humidity"]      = simulatedHumidity;
  doc["light"]         = simulatedLight;
  doc["soilMoisture"]  = simulatedSoil;
  doc["rssi"]          = rssi;
  doc["ipAddress"]     = WiFi.localIP().toString();

  String requestBody;
  serializeJson(doc, requestBody);

  Serial.println("[Cloud] Sending telemetry packet...");
  int httpCode = http.POST(requestBody);

  if (httpCode > 0) {
    String responseString = http.getString();
    Serial.printf("[Cloud] Success (HTTP %d)\\n", httpCode);

    // 3. Parse Server Response for Remote Actuator Commands
    StaticJsonDocument<512> responseDoc;
    DeserializationError error = deserializeJson(responseDoc, responseString);

    if (!error) {
      JsonObject actuators = responseDoc["actuatorStates"];
      if (!actuators.isNull()) {
        // Example: Check if pin_2 / pump relay was toggled from web dashboard
        if (actuators.containsKey("pin_2")) {
          bool pumpState = actuators["pin_2"].as<bool>();
          digitalWrite(RELAY_PIN_PUMP, pumpState ? HIGH : LOW);
          Serial.printf("[Actuator] Pin 2 Relay set to: %s\\n", pumpState ? "ON" : "OFF");
        }
      }
    }
  } else {
    Serial.printf("[Cloud] Telemetry failed. Error: %s\\n", http.errorToString(httpCode).c_str());
  }

  http.end();
}
`;
}
