import { Category, Department, Resource, NewsArticle, OfficialLink, AdminActivityLog, ResourceSubmission } from '@/types/database';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Official Forms',
    slug: 'forms',
    description: 'Standard application, request, and clearance documents for students and personnel.',
    parent_id: null,
    sort_order: 1,
    is_active: true,
    icon: 'FileText',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Templates',
    slug: 'templates',
    description: 'Standardized document layouts, presentation decks, syllabus formats, and letterheads.',
    parent_id: null,
    sort_order: 2,
    is_active: true,
    icon: 'Layout',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Policies & Guidelines',
    slug: 'policies-guidelines',
    description: 'Institutional codes, student handbooks, faculty manuals, and academic guidelines.',
    parent_id: null,
    sort_order: 3,
    is_active: true,
    icon: 'ShieldCheck',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Memorandums',
    slug: 'memorandums',
    description: 'Official university circulars, executive orders, and administrative directives.',
    parent_id: null,
    sort_order: 4,
    is_active: true,
    icon: 'Megaphone',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'Academic & Curriculum',
    slug: 'academic',
    description: 'Academic calendars, grading systems, course revision guidelines, and syllabi.',
    parent_id: null,
    sort_order: 5,
    is_active: true,
    icon: 'GraduationCap',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-6',
    name: 'Research & Ethics',
    slug: 'research',
    description: 'Research grant proposals, ethics review protocols, IP filing forms, and publication grants.',
    parent_id: null,
    sort_order: 6,
    is_active: true,
    icon: 'Flask',
    created_at: '2026-01-10T00:00:00Z',
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Office of the University Registrar',
    slug: 'registrar',
    abbreviation: 'OUR',
    description: 'Academic records, enrollment verification, transcript requests, and graduation clearances.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'Human Resource Management Office',
    slug: 'human-resources',
    abbreviation: 'HRMO',
    description: 'Faculty and staff benefits, employment certifications, leave forms, and hiring protocols.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Office of Student Affairs and Services',
    slug: 'student-affairs',
    abbreviation: 'OSAS',
    description: 'Student organization recognition, scholarships, counseling, and discipline guidelines.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'University Research and Development Center',
    slug: 'research-center',
    abbreviation: 'URDC',
    description: 'Research funding, institutional ethics approval, patent disclosures, and journal publications.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-5',
    name: 'Information and Communications Technology Office',
    slug: 'ict-office',
    abbreviation: 'ICTO',
    description: 'University email requests, portal credentials, network access, and software licenses.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-6',
    name: 'Accounting and Financial Services Office',
    slug: 'accounting',
    abbreviation: 'AFSO',
    description: 'Tuition statements, refund requests, official receipts, and procurement liquidation forms.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const mockResources: Resource[] = [
  {
    id: 'res-1',
    title: 'Application for Transcript of Records & Academic Certification',
    slug: 'application-transcript-of-records-certification',
    description:
      'Official form required by the Office of the University Registrar to request official transcripts, honorable dismissals, diplomas, and general certificates of enrollment or graduation.',
    category_id: 'cat-1',
    department_id: 'dept-1',
    document_type: 'form',
    file_path: '/documents/OUR-Form-01-OTR-Request-2026.pdf',
    file_name: 'OUR-Form-01-OTR-Request-2026.pdf',
    file_format: 'PDF',
    file_size: 428000, // ~418 KB
    current_version: '2026.1',
    status: 'active',
    source_name: 'Office of the University Registrar',
    source_url: 'https://university.edu/registrar/forms/otr-2026',
    is_featured: true,
    download_count: 1482,
    created_by: 'admin-1',
    created_at: '2026-01-15T08:30:00Z',
    updated_at: '2026-02-01T10:00:00Z',
    category: mockCategories[0],
    department: mockDepartments[0],
    tags: [
      { id: 't-1', name: 'Transcript', slug: 'transcript', created_at: '' },
      { id: 't-2', name: 'Registrar', slug: 'registrar', created_at: '' },
      { id: 't-3', name: 'Graduation', slug: 'graduation', created_at: '' },
    ],
  },
  {
    id: 'res-2',
    title: 'Faculty & Staff Application for Leave of Absence (Form 6)',
    slug: 'application-leave-of-absence-form-6',
    description:
      'Standard Civil Service / University Form 6 for vacation, sick, study, maternity, paternity, or special privilege leave filing. Requires department head and HR endorsement.',
    category_id: 'cat-1',
    department_id: 'dept-2',
    document_type: 'form',
    file_path: '/documents/HRMO-Form-06-Leave-Application-Rev2026.docx',
    file_name: 'HRMO-Form-06-Leave-Application-Rev2026.docx',
    file_format: 'DOCX',
    file_size: 185000, // ~180 KB
    current_version: '2026.2',
    status: 'active',
    source_name: 'Human Resource Management Office',
    source_url: 'https://university.edu/hrmo/downloads/leave-form',
    is_featured: true,
    download_count: 893,
    created_by: 'admin-1',
    created_at: '2026-01-18T09:15:00Z',
    updated_at: '2026-01-20T14:30:00Z',
    category: mockCategories[0],
    department: mockDepartments[1],
    tags: [
      { id: 't-4', name: 'Leave', slug: 'leave', created_at: '' },
      { id: 't-5', name: 'HR', slug: 'hr', created_at: '' },
      { id: 't-6', name: 'Faculty', slug: 'faculty', created_at: '' },
    ],
  },
  {
    id: 'res-3',
    title: 'Official University Presentation & Master Thesis Slide Deck Template',
    slug: 'official-university-presentation-slide-deck-template',
    description:
      'Standard 16:9 widescreen PowerPoint and Google Slides template adhering to institutional brand standards, university crests, approved color typography, and thesis defense layout guidelines.',
    category_id: 'cat-2',
    department_id: 'dept-5',
    document_type: 'template',
    file_path: '/documents/UNI-Master-Presentation-Template-16x9.pptx',
    file_name: 'UNI-Master-Presentation-Template-16x9.pptx',
    file_format: 'PPTX',
    file_size: 2450000, // ~2.4 MB
    current_version: '2026.0',
    status: 'active',
    source_name: 'ICTO & Brand Communications Bureau',
    source_url: 'https://university.edu/brand/templates/slides',
    is_featured: true,
    download_count: 2150,
    created_by: 'admin-1',
    created_at: '2026-01-05T11:00:00Z',
    updated_at: '2026-01-05T11:00:00Z',
    category: mockCategories[1],
    department: mockDepartments[4],
    tags: [
      { id: 't-7', name: 'Slide Deck', slug: 'slide-deck', created_at: '' },
      { id: 't-8', name: 'Brand', slug: 'brand', created_at: '' },
      { id: 't-9', name: 'Thesis', slug: 'thesis', created_at: '' },
    ],
  },
  {
    id: 'res-4',
    title: 'Student Handbook & Code of Academic Integrity (2025–2028 Edition)',
    slug: 'student-handbook-code-of-academic-integrity',
    description:
      'Comprehensive compilation of student rights, campus safety policies, grading systems, organization accreditation protocols, scholarship guidelines, and disciplinary procedures.',
    category_id: 'cat-3',
    department_id: 'dept-3',
    document_type: 'policy',
    file_path: '/documents/OSAS-Student-Handbook-2025-2028.pdf',
    file_name: 'OSAS-Student-Handbook-2025-2028.pdf',
    file_format: 'PDF',
    file_size: 4890000, // ~4.8 MB
    current_version: '2025–2028',
    status: 'active',
    source_name: 'Office of Student Affairs and Services',
    source_url: 'https://university.edu/osas/handbook',
    is_featured: true,
    download_count: 3410,
    created_by: 'admin-1',
    created_at: '2025-11-20T08:00:00Z',
    updated_at: '2026-01-12T16:00:00Z',
    category: mockCategories[2],
    department: mockDepartments[2],
    tags: [
      { id: 't-10', name: 'Handbook', slug: 'handbook', created_at: '' },
      { id: 't-11', name: 'Policies', slug: 'policies', created_at: '' },
      { id: 't-12', name: 'Students', slug: 'students', created_at: '' },
    ],
  },
  {
    id: 'res-5',
    title: 'University Research Ethics Review Protocol & Clearance Submission Form',
    slug: 'research-ethics-review-protocol-form',
    description:
      'Institutional Ethics Committee compliance packet for research involving human participants, data privacy clearance, informed consent templates, and clinical evaluation questionnaires.',
    category_id: 'cat-6',
    department_id: 'dept-4',
    document_type: 'form',
    file_path: '/documents/URDC-Ethics-Packet-Form-A1-2026.pdf',
    file_name: 'URDC-Ethics-Packet-Form-A1-2026.pdf',
    file_format: 'PDF',
    file_size: 612000, // ~600 KB
    current_version: '2026.1',
    status: 'active',
    source_name: 'University Research and Development Center',
    source_url: 'https://university.edu/urdc/ethics-committee',
    is_featured: false,
    download_count: 512,
    created_by: 'admin-1',
    created_at: '2026-02-02T13:40:00Z',
    updated_at: '2026-02-02T13:40:00Z',
    category: mockCategories[5],
    department: mockDepartments[3],
    tags: [
      { id: 't-13', name: 'Ethics', slug: 'ethics', created_at: '' },
      { id: 't-14', name: 'Research', slug: 'research', created_at: '' },
    ],
  },
  {
    id: 'res-6',
    title: 'Memorandum Circular No. 04: Guidelines on Hybrid Teaching and Academic Work Schedule',
    slug: 'memo-04-guidelines-hybrid-teaching-schedule',
    description:
      'Executive directive from the Office of the University President detailing synchronous virtual days, classroom occupancy limits, and faculty consultation hours.',
    category_id: 'cat-4',
    department_id: 'dept-1',
    document_type: 'memorandum',
    file_path: '/documents/OP-Memo-2026-04-Hybrid-Teaching.pdf',
    file_name: 'OP-Memo-2026-04-Hybrid-Teaching.pdf',
    file_format: 'PDF',
    file_size: 290000,
    current_version: '2026-04',
    status: 'active',
    source_name: 'Office of the University President',
    source_url: 'https://university.edu/president/memos/2026-04',
    is_featured: false,
    download_count: 730,
    created_by: 'admin-1',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
    category: mockCategories[3],
    department: mockDepartments[0],
    tags: [
      { id: 't-15', name: 'Memorandum', slug: 'memorandum', created_at: '' },
      { id: 't-16', name: 'Hybrid', slug: 'hybrid', created_at: '' },
    ],
  },
  {
    id: 'res-7',
    title: 'University Travel Expense Liquidation & Cash Advance Settlement Workbook',
    slug: 'travel-expense-liquidation-settlement-workbook',
    description:
      'Automated Excel spreadsheet with built-in formulas for per diem calculations, transportation allowance breakdowns, and receipt accounting for official university trips.',
    category_id: 'cat-1',
    department_id: 'dept-6',
    document_type: 'form',
    file_path: '/documents/AFSO-Liquidation-Workbook-v4.xlsx',
    file_name: 'AFSO-Liquidation-Workbook-v4.xlsx',
    file_format: 'XLSX',
    file_size: 320000,
    current_version: 'v4.2',
    status: 'active',
    source_name: 'Accounting and Financial Services Office',
    source_url: 'https://university.edu/accounting/forms/travel-liquidation',
    is_featured: false,
    download_count: 640,
    created_by: 'admin-1',
    created_at: '2026-01-25T15:20:00Z',
    updated_at: '2026-01-25T15:20:00Z',
    category: mockCategories[0],
    department: mockDepartments[5],
    tags: [
      { id: 't-17', name: 'Finance', slug: 'finance', created_at: '' },
      { id: 't-18', name: 'Liquidation', slug: 'liquidation', created_at: '' },
    ],
  },
  {
    id: 'res-8',
    title: 'Course Syllabus Template & Outcome-Based Education (OBE) Matrix',
    slug: 'course-syllabus-template-obe-matrix',
    description:
      'Standard template approved by the Academic Council for crafting undergraduate and graduate syllabi, mapping course learning outcomes (CLOs) to program educational objectives.',
    category_id: 'cat-2',
    department_id: 'dept-1',
    document_type: 'template',
    file_path: '/documents/VPAA-OBE-Syllabus-Template-2026.docx',
    file_name: 'VPAA-OBE-Syllabus-Template-2026.docx',
    file_format: 'DOCX',
    file_size: 215000,
    current_version: '2026.0',
    status: 'active',
    source_name: 'Vice President for Academic Affairs',
    source_url: 'https://university.edu/vpaa/obe-syllabus',
    is_featured: true,
    download_count: 1190,
    created_by: 'admin-1',
    created_at: '2026-01-08T09:00:00Z',
    updated_at: '2026-01-08T09:00:00Z',
    category: mockCategories[1],
    department: mockDepartments[0],
    tags: [
      { id: 't-19', name: 'Syllabus', slug: 'syllabus', created_at: '' },
      { id: 't-20', name: 'OBE', slug: 'obe', created_at: '' },
      { id: 't-21', name: 'Faculty', slug: 'faculty', created_at: '' },
    ],
  },
];

export const mockNewsArticles: NewsArticle[] = [
  {
    id: 'news-1',
    source_id: 'src-1',
    title: 'University Opens Applications for 2026 Academic Excellence & Leadership Scholarships',
    summary:
      'The Office of Student Affairs has officially announced the opening of scholarship applications for undergraduate students with exceptional academic standing. Deadline for submission is March 31, 2026.',
    content_url: 'https://university.edu/news/scholarship-applications-2026',
    image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-3',
    status: 'approved',
    is_featured: true,
    external_id: 'rss-item-101',
    reviewed_by: 'admin-1',
    published_at: '2026-02-24T08:00:00Z',
    fetched_at: '2026-02-24T06:00:00Z',
    reviewed_at: '2026-02-24T07:30:00Z',
    created_at: '2026-02-24T06:00:00Z',
    department: mockDepartments[2],
  },
  {
    id: 'news-2',
    source_id: 'src-1',
    title: 'Registrar Announces Digital Clearance Protocol for Mid-Year Graduating Cohort',
    summary:
      'All candidates for graduation are advised to complete their digital clearance via the Resursee portal before claiming their formal degree credentials and transcripts.',
    content_url: 'https://university.edu/registrar/announcements/clearance-2026',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-1',
    status: 'approved',
    is_featured: true,
    external_id: 'rss-item-102',
    reviewed_by: 'admin-1',
    published_at: '2026-02-20T11:00:00Z',
    fetched_at: '2026-02-20T09:00:00Z',
    reviewed_at: '2026-02-20T10:00:00Z',
    created_at: '2026-02-20T09:00:00Z',
    department: mockDepartments[0],
  },
  {
    id: 'news-3',
    source_id: 'src-2',
    title: 'URDC Secures National Research Grants for AI in Agriculture and Smart Campus Initiatives',
    summary:
      'Three university faculty research teams were awarded competitive research development grants amounting to ₱15 Million for advanced environmental sensing and sustainable agriculture.',
    content_url: 'https://university.edu/research/grants-awarded-feb2026',
    image_url: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-4',
    status: 'approved',
    is_featured: false,
    external_id: 'rss-item-103',
    reviewed_by: 'admin-1',
    published_at: '2026-02-15T14:30:00Z',
    fetched_at: '2026-02-15T12:00:00Z',
    reviewed_at: '2026-02-15T13:00:00Z',
    created_at: '2026-02-15T12:00:00Z',
    department: mockDepartments[3],
  },
  {
    id: 'news-4',
    source_id: 'src-1',
    title: 'Campus IT Advisory: Scheduled Maintenance and Single Sign-On Infrastructure Upgrade',
    summary:
      'University central portal services and email directories will undergo scheduled optimization on Saturday from 10:00 PM to 4:00 AM to enhance response latency and security.',
    content_url: 'https://university.edu/icto/advisories/maintenance-feb2026',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-5',
    status: 'approved',
    is_featured: false,
    external_id: 'rss-item-104',
    reviewed_by: 'admin-1',
    published_at: '2026-02-12T16:00:00Z',
    fetched_at: '2026-02-12T14:00:00Z',
    reviewed_at: '2026-02-12T15:00:00Z',
    created_at: '2026-02-12T14:00:00Z',
    department: mockDepartments[4],
  },
  {
    id: 'news-5',
    source_id: 'src-1',
    title: '[Pending Review] Faculty Development Seminar on Generative AI Ethics in Higher Education',
    summary:
      'A mandatory workshop for teaching faculty on integrating ethical AI guidelines, curriculum integrity, and modern assessment methods.',
    content_url: 'https://university.edu/vpaa/events/ai-seminar-2026',
    image_url: null,
    department_id: 'dept-1',
    status: 'pending',
    is_featured: false,
    external_id: 'rss-item-105',
    reviewed_by: null,
    published_at: null,
    fetched_at: '2026-02-26T18:00:00Z',
    reviewed_at: null,
    created_at: '2026-02-26T18:00:00Z',
    department: mockDepartments[0],
  },
];

export const mockOfficialLinks: OfficialLink[] = [
  {
    id: 'link-1',
    title: 'University Main Portal & Student Information System',
    url: 'https://portal.university.edu',
    description: 'Access student grades, enrollment records, class schedules, and fee balance statements.',
    category: 'Portals',
    sort_order: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-2',
    title: 'University Learning Management System (LMS)',
    url: 'https://lms.university.edu',
    description: 'Course modules, assignment submissions, virtual lecture rooms, and quizzes.',
    category: 'Portals',
    sort_order: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-3',
    title: 'University Library Online Public Access Catalog (OPAC)',
    url: 'https://library.university.edu',
    description: 'Search physical library book inventory, IEEE/Scopus subscriptions, and digital thesis repository.',
    category: 'Academic Services',
    sort_order: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-4',
    title: 'Human Resource Management Portal',
    url: 'https://hrmo.university.edu',
    description: 'Personnel records, service credits, biometric attendance summaries, and payslips.',
    category: 'Administrative Services',
    sort_order: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-5',
    title: 'University Research & Publication Database',
    url: 'https://research.university.edu',
    description: 'Peer-reviewed faculty journals, research repositories, and citation indexes.',
    category: 'Research & Innovation',
    sort_order: 5,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-6',
    title: 'ICTO Helpdesk & Campus Wi-Fi Support',
    url: 'https://helpdesk.university.edu',
    description: 'Submit IT support tickets, password resets, and network connectivity inquiries.',
    category: 'Technical Support',
    sort_order: 6,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const mockActivityLogs: AdminActivityLog[] = [
  {
    id: 'act-1',
    admin_id: 'admin-1',
    action: 'CREATE_RESOURCE',
    entity_type: 'resource',
    entity_id: 'res-1',
    details: { title: 'Application for Transcript of Records & Academic Certification', version: '2026.1' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-26T21:40:00Z',
    admin_email: 'admin@university.edu',
  },
  {
    id: 'act-2',
    admin_id: 'admin-1',
    action: 'APPROVE_NEWS',
    entity_type: 'news_article',
    entity_id: 'news-1',
    details: { title: 'University Opens Applications for 2026 Scholarships' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-24T07:30:00Z',
    admin_email: 'admin@university.edu',
  },
  {
    id: 'act-3',
    admin_id: 'admin-1',
    action: 'UPDATE_CATEGORY',
    entity_type: 'category',
    entity_id: 'cat-1',
    details: { name: 'Official Forms', previous: 'Forms' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-20T14:10:00Z',
    admin_email: 'admin@university.edu',
  },
];

export const mockSubmissions: ResourceSubmission[] = [
  {
    id: 'sub-1',
    title: 'Student Organization Financial Clearance & Auditing Form 2026',
    description:
      'Newly updated annual financial clearance protocol and expense verification worksheet issued by the Student Council and Student Affairs for accredited campus organizations.',
    category_id: 'cat-1',
    department_id: 'dept-3',
    document_type: 'form',
    file_name: 'OSAS-Org-Financial-Clearance-2026.pdf',
    file_format: 'PDF',
    file_size: 345000,
    file_path: '/documents/OSAS-Org-Financial-Clearance-2026.pdf',
    version_label: '2026.1',
    source_name: 'Office of Student Affairs and Services (OSAS)',
    source_url: 'https://university.edu/osas/forms/org-clearance-2026',
    submission_type: 'new_resource',
    existing_resource_id: null,
    submitter_name: 'Michael Angelo Rivera',
    submitter_email: 'marivera@university.edu',
    submitter_role: 'student',
    submission_notes:
      'This form was released last week during the Student Council General Assembly. It replaces the 2024 physical clearance sheet with digital signature endorsements.',
    status: 'pending',
    created_at: '2026-02-26T14:20:00Z',
    category: mockCategories[0],
    department: mockDepartments[2],
  },
  {
    id: 'sub-2',
    title: 'Updated Faculty Research Seed Grant Application Packet (Rev 2026)',
    description:
      'Updated budget allocation worksheets, co-investigator agreement annexes, and timeline Gantt chart template for internally funded faculty research.',
    category_id: 'cat-6',
    department_id: 'dept-4',
    document_type: 'template',
    file_name: 'URDC-Faculty-Seed-Grant-Packet-Rev2026.docx',
    file_format: 'DOCX',
    file_size: 512000,
    file_path: '/documents/URDC-Faculty-Seed-Grant-Packet-Rev2026.docx',
    version_label: '2026.2',
    source_name: 'University Research and Development Center (URDC)',
    source_url: 'https://university.edu/urdc/grants/seed-funding-2026',
    submission_type: 'update_existing',
    existing_resource_id: 'res-5',
    submitter_name: 'Dr. Elena Santos-Cruz',
    submitter_email: 'escruz@university.edu',
    submitter_role: 'faculty',
    submission_notes:
      'The URDC council updated the maximum per-project equipment cap from ₱100k to ₱250k. Please update the current version on the portal.',
    status: 'pending',
    created_at: '2026-02-25T19:45:00Z',
    category: mockCategories[5],
    department: mockDepartments[3],
  },
  {
    id: 'sub-3',
    title: 'University Audio-Visual & Campus Multi-Purpose Hall Reservation Permit',
    slug: 'campus-facility-reservation-permit-2026',
    description:
      'Booking requisition permit for multi-purpose gymnasium, AVR theaters, sound system tech crew, and university vehicle convoy.',
    category_id: 'cat-1',
    department_id: 'dept-5',
    document_type: 'form',
    file_name: 'ICTO-Facility-Convoy-Permit-2026.pdf',
    file_format: 'PDF',
    file_size: 275000,
    version_label: '2026.0',
    source_name: 'ICTO & Physical Facilities Office',
    source_url: 'https://university.edu/facilities/permits',
    submission_type: 'new_resource',
    existing_resource_id: null,
    submitter_name: 'Engr. Roberto Gomez',
    submitter_email: 'rgomez@university.edu',
    submitter_role: 'staff',
    submission_notes: 'Standard requisition permit for 2026 campus events.',
    status: 'approved',
    reviewed_by: 'admin-master',
    reviewed_at: '2026-02-23T11:00:00Z',
    created_at: '2026-02-22T08:15:00Z',
    category: mockCategories[0],
    department: mockDepartments[4],
  } as any,
];

