import { Category, Department, Resource, NewsArticle, OfficialLink, AdminActivityLog, ResourceSubmission } from '@/types/database';

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Official Forms',
    slug: 'forms',
    description: 'Standard application, request, and clearance documents for students and personnel.',
    parent_id: null,
    sort_order: 1,
    is_active: true,
    icon: 'FileText',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-2',
    name: 'Templates',
    slug: 'templates',
    description: 'Standardized document layouts, presentation decks, syllabus formats, and letterheads.',
    parent_id: null,
    sort_order: 2,
    is_active: true,
    icon: 'Layout',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-3',
    name: 'Policies & Guidelines',
    slug: 'policies-guidelines',
    description: 'Institutional codes, student handbooks, faculty manuals, and academic guidelines.',
    parent_id: null,
    sort_order: 3,
    is_active: true,
    icon: 'ShieldCheck',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-4',
    name: 'Memorandums',
    slug: 'memorandums',
    description: 'Official university circulars, executive orders, and administrative directives.',
    parent_id: null,
    sort_order: 4,
    is_active: true,
    icon: 'Megaphone',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-5',
    name: 'Academic & Curriculum',
    slug: 'academic',
    description: 'Academic calendars, grading systems, course revision guidelines, and syllabi.',
    parent_id: null,
    sort_order: 5,
    is_active: true,
    icon: 'GraduationCap',
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'cat-6',
    name: 'Research & Ethics',
    slug: 'research',
    description: 'Research grant proposals, ethics review protocols, IP filing forms, and publication grants.',
    parent_id: null,
    sort_order: 6,
    is_active: true,
    icon: 'Flask',
    created_at: '2026-01-10T00:00:00Z',
  },
];

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Office of the University Registrar',
    slug: 'registrar',
    abbreviation: 'OUR',
    description: 'Academic records, enrollment verification, transcript requests, and graduation clearances.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-2',
    name: 'Human Resource Management Office',
    slug: 'human-resources',
    abbreviation: 'HRMO',
    description: 'Faculty and staff benefits, employment certifications, leave forms, and hiring protocols.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-3',
    name: 'Office of Student Affairs and Services',
    slug: 'student-affairs',
    abbreviation: 'OSAS',
    description: 'Student organization recognition, scholarships, counseling, and discipline guidelines.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-4',
    name: 'University Research and Development Center',
    slug: 'research-center',
    abbreviation: 'URDC',
    description: 'Research funding, institutional ethics approval, patent disclosures, and journal publications.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-5',
    name: 'Information and Communications Technology Office',
    slug: 'ict-office',
    abbreviation: 'ICTO',
    description: 'University email requests, portal credentials, network access, and software licenses.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'dept-6',
    name: 'Accounting and Financial Services Office',
    slug: 'accounting',
    abbreviation: 'AFSO',
    description: 'Tuition statements, refund requests, official receipts, and procurement liquidation forms.',
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const mockResources: Resource[] = [];

export const mockNewsArticles: NewsArticle[] = [
  {
    id: 'news-1',
    source_id: 'src-1',
    title: 'University Opens Applications for 2026 Academic Excellence & Leadership Scholarships',
    summary:
      'The Office of Student Affairs has officially announced the opening of scholarship applications for undergraduate students with exceptional academic standing. Deadline for submission is March 31, 2026.',
    content_url: 'https://university.edu/news/scholarship-applications-2026',
    image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-3',
    status: 'approved',
    is_featured: true,
    external_id: 'rss-item-101',
    reviewed_by: 'admin-1',
    published_at: '2026-02-24T08:00:00Z',
    fetched_at: '2026-02-24T06:00:00Z',
    reviewed_at: '2026-02-24T07:30:00Z',
    created_at: '2026-02-24T06:00:00Z',
    department: mockDepartments[2],
  },
  {
    id: 'news-2',
    source_id: 'src-1',
    title: 'Registrar Announces Digital Clearance Protocol for Mid-Year Graduating Cohort',
    summary:
      'All candidates for graduation are advised to complete their digital clearance via the Resursee portal before claiming their formal degree credentials and transcripts.',
    content_url: 'https://university.edu/registrar/announcements/clearance-2026',
    image_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-1',
    status: 'approved',
    is_featured: true,
    external_id: 'rss-item-102',
    reviewed_by: 'admin-1',
    published_at: '2026-02-20T11:00:00Z',
    fetched_at: '2026-02-20T09:00:00Z',
    reviewed_at: '2026-02-20T10:00:00Z',
    created_at: '2026-02-20T09:00:00Z',
    department: mockDepartments[0],
  },
  {
    id: 'news-3',
    source_id: 'src-2',
    title: 'URDC Secures National Research Grants for AI in Agriculture and Smart Campus Initiatives',
    summary:
      'Three university faculty research teams were awarded competitive research development grants amounting to ₱15 Million for advanced environmental sensing and sustainable agriculture.',
    content_url: 'https://university.edu/research/grants-awarded-feb2026',
    image_url: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-4',
    status: 'approved',
    is_featured: false,
    external_id: 'rss-item-103',
    reviewed_by: 'admin-1',
    published_at: '2026-02-15T14:30:00Z',
    fetched_at: '2026-02-15T12:00:00Z',
    reviewed_at: '2026-02-15T13:00:00Z',
    created_at: '2026-02-15T12:00:00Z',
    department: mockDepartments[3],
  },
  {
    id: 'news-4',
    source_id: 'src-1',
    title: 'Campus IT Advisory: Scheduled Maintenance and Single Sign-On Infrastructure Upgrade',
    summary:
      'University central portal services and email directories will undergo scheduled optimization on Saturday from 10:00 PM to 4:00 AM to enhance response latency and security.',
    content_url: 'https://university.edu/icto/advisories/maintenance-feb2026',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&auto=format&fit=crop&q=80',
    department_id: 'dept-5',
    status: 'approved',
    is_featured: false,
    external_id: 'rss-item-104',
    reviewed_by: 'admin-1',
    published_at: '2026-02-12T16:00:00Z',
    fetched_at: '2026-02-12T14:00:00Z',
    reviewed_at: '2026-02-12T15:00:00Z',
    created_at: '2026-02-12T14:00:00Z',
    department: mockDepartments[4],
  },
  {
    id: 'news-5',
    source_id: 'src-1',
    title: '[Pending Review] Faculty Development Seminar on Generative AI Ethics in Higher Education',
    summary:
      'A mandatory workshop for teaching faculty on integrating ethical AI guidelines, curriculum integrity, and modern assessment methods.',
    content_url: 'https://university.edu/vpaa/events/ai-seminar-2026',
    image_url: null,
    department_id: 'dept-1',
    status: 'pending',
    is_featured: false,
    external_id: 'rss-item-105',
    reviewed_by: null,
    published_at: null,
    fetched_at: '2026-02-26T18:00:00Z',
    reviewed_at: null,
    created_at: '2026-02-26T18:00:00Z',
    department: mockDepartments[0],
  },
];

export const mockOfficialLinks: OfficialLink[] = [
  {
    id: 'link-1',
    title: 'University Main Portal & Student Information System',
    url: 'https://portal.university.edu',
    description: 'Access student grades, enrollment records, class schedules, and fee balance statements.',
    category: 'Portals',
    sort_order: 1,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-2',
    title: 'University Learning Management System (LMS)',
    url: 'https://lms.university.edu',
    description: 'Course modules, assignment submissions, virtual lecture rooms, and quizzes.',
    category: 'Portals',
    sort_order: 2,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-3',
    title: 'University Library Online Public Access Catalog (OPAC)',
    url: 'https://library.university.edu',
    description: 'Search physical library book inventory, IEEE/Scopus subscriptions, and digital thesis repository.',
    category: 'Academic Services',
    sort_order: 3,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-4',
    title: 'Human Resource Management Portal',
    url: 'https://hrmo.university.edu',
    description: 'Personnel records, service credits, biometric attendance summaries, and payslips.',
    category: 'Administrative Services',
    sort_order: 4,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-5',
    title: 'University Research & Publication Database',
    url: 'https://research.university.edu',
    description: 'Peer-reviewed faculty journals, research repositories, and citation indexes.',
    category: 'Research & Innovation',
    sort_order: 5,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'link-6',
    title: 'ICTO Helpdesk & Campus Wi-Fi Support',
    url: 'https://helpdesk.university.edu',
    description: 'Submit IT support tickets, password resets, and network connectivity inquiries.',
    category: 'Technical Support',
    sort_order: 6,
    is_active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const mockActivityLogs: AdminActivityLog[] = [
  {
    id: 'act-1',
    admin_id: 'admin-1',
    action: 'CREATE_RESOURCE',
    entity_type: 'resource',
    entity_id: 'res-1',
    details: { title: 'Application for Transcript of Records & Academic Certification', version: '2026.1' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-26T21:40:00Z',
    admin_email: 'admin@university.edu',
  },
  {
    id: 'act-2',
    admin_id: 'admin-1',
    action: 'APPROVE_NEWS',
    entity_type: 'news_article',
    entity_id: 'news-1',
    details: { title: 'University Opens Applications for 2026 Scholarships' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-24T07:30:00Z',
    admin_email: 'admin@university.edu',
  },
  {
    id: 'act-3',
    admin_id: 'admin-1',
    action: 'UPDATE_CATEGORY',
    entity_type: 'category',
    entity_id: 'cat-1',
    details: { name: 'Official Forms', previous: 'Forms' },
    ip_address: '192.168.1.1',
    created_at: '2026-02-20T14:10:00Z',
    admin_email: 'admin@university.edu',
  },
];

export const mockSubmissions: ResourceSubmission[] = [
  {
    id: 'sub-1',
    title: 'Student Organization Financial Clearance & Auditing Form 2026',
    description:
      'Newly updated annual financial clearance protocol and expense verification worksheet issued by the Student Council and Student Affairs for accredited campus organizations.',
    category_id: 'cat-1',
    department_id: 'dept-3',
    document_type: 'form',
    file_name: 'OSAS-Org-Financial-Clearance-2026.pdf',
    file_format: 'PDF',
    file_size: 345000,
    file_path: '/documents/OSAS-Org-Financial-Clearance-2026.pdf',
    version_label: '2026.1',
    source_name: 'Office of Student Affairs and Services (OSAS)',
    source_url: 'https://university.edu/osas/forms/org-clearance-2026',
    submission_type: 'new_resource',
    existing_resource_id: null,
    submitter_name: 'Michael Angelo Rivera',
    submitter_email: 'marivera@university.edu',
    submitter_role: 'student',
    submission_notes:
      'This form was released last week during the Student Council General Assembly. It replaces the 2024 physical clearance sheet with digital signature endorsements.',
    status: 'pending',
    created_at: '2026-02-26T14:20:00Z',
    category: mockCategories[0],
    department: mockDepartments[2],
  },
  {
    id: 'sub-2',
    title: 'Updated Faculty Research Seed Grant Application Packet (Rev 2026)',
    description:
      'Updated budget allocation worksheets, co-investigator agreement annexes, and timeline Gantt chart template for internally funded faculty research.',
    category_id: 'cat-6',
    department_id: 'dept-4',
    document_type: 'template',
    file_name: 'URDC-Faculty-Seed-Grant-Packet-Rev2026.docx',
    file_format: 'DOCX',
    file_size: 512000,
    file_path: '/documents/URDC-Faculty-Seed-Grant-Packet-Rev2026.docx',
    version_label: '2026.2',
    source_name: 'University Research and Development Center (URDC)',
    source_url: 'https://university.edu/urdc/grants/seed-funding-2026',
    submission_type: 'update_existing',
    existing_resource_id: 'res-5',
    submitter_name: 'Dr. Elena Santos-Cruz',
    submitter_email: 'escruz@university.edu',
    submitter_role: 'faculty',
    submission_notes:
      'The URDC council updated the maximum per-project equipment cap from ₱100k to ₱250k. Please update the current version on the portal.',
    status: 'pending',
    created_at: '2026-02-25T19:45:00Z',
    category: mockCategories[5],
    department: mockDepartments[3],
  },
  {
    id: 'sub-3',
    title: 'University Audio-Visual & Campus Multi-Purpose Hall Reservation Permit',
    slug: 'campus-facility-reservation-permit-2026',
    description:
      'Booking requisition permit for multi-purpose gymnasium, AVR theaters, sound system tech crew, and university vehicle convoy.',
    category_id: 'cat-1',
    department_id: 'dept-5',
    document_type: 'form',
    file_name: 'ICTO-Facility-Convoy-Permit-2026.pdf',
    file_format: 'PDF',
    file_size: 275000,
    version_label: '2026.0',
    source_name: 'ICTO & Physical Facilities Office',
    source_url: 'https://university.edu/facilities/permits',
    submission_type: 'new_resource',
    existing_resource_id: null,
    submitter_name: 'Engr. Roberto Gomez',
    submitter_email: 'rgomez@university.edu',
    submitter_role: 'staff',
    submission_notes: 'Standard requisition permit for 2026 campus events.',
    status: 'approved',
    reviewed_by: 'admin-master',
    reviewed_at: '2026-02-23T11:00:00Z',
    created_at: '2026-02-22T08:15:00Z',
    category: mockCategories[0],
    department: mockDepartments[4],
  } as any,
];

