import { TechTheme, TechThemeId } from '@/types/presentation';

export const TECH_THEMES: Record<TechThemeId, TechTheme> = {
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian Terminal',
    description: 'Deep obsidian backdrop with high-contrast jet typography, monospace telemetry, and crisp card borders.',
    badge: 'Terminal Dark',
    bgClass: 'bg-[#09090b]',
    canvasBg: '#09090b',
    surfaceClass: 'bg-[#121215] border border-neutral-800 text-neutral-100',
    textClass: 'text-white',
    subtextClass: 'text-neutral-400',
    borderClass: 'border-neutral-800',
    accentColor: '#ffffff',
    accentBadgeClass: 'bg-neutral-800 text-neutral-200 border border-neutral-700',
    fontFamily: 'font-mono',
    previewColors: {
      bg: '#09090b',
      surface: '#121215',
      accent: '#ffffff',
      text: '#fafafa',
    },
  },
  silicon: {
    id: 'silicon',
    name: 'Silicon Slate',
    description: 'Deep navy-slate engineering surface with crisp ice-silver typography and structured blueprint cards.',
    badge: 'Enterprise Slate',
    bgClass: 'bg-[#0b1329]',
    canvasBg: '#0b1329',
    surfaceClass: 'bg-[#111c38] border border-slate-700/80 text-slate-100',
    textClass: 'text-white',
    subtextClass: 'text-slate-400',
    borderClass: 'border-slate-800',
    accentColor: '#cbd5e1',
    accentBadgeClass: 'bg-slate-800 text-slate-200 border border-slate-700',
    fontFamily: 'font-sans',
    previewColors: {
      bg: '#0b1329',
      surface: '#111c38',
      accent: '#94a3b8',
      text: '#f8fafc',
    },
  },
  quantum: {
    id: 'quantum',
    name: 'Quantum Monochrome',
    description: 'High-contrast pure black and pure white neo-grotesque design with maximum legibility and architectural lines.',
    badge: 'Pure Monochrome',
    bgClass: 'bg-black',
    canvasBg: '#000000',
    surfaceClass: 'bg-neutral-900 border border-neutral-700 text-white',
    textClass: 'text-white',
    subtextClass: 'text-neutral-300',
    borderClass: 'border-neutral-700',
    accentColor: '#ffffff',
    accentBadgeClass: 'bg-white text-black font-black border border-white',
    fontFamily: 'font-sans',
    previewColors: {
      bg: '#000000',
      surface: '#171717',
      accent: '#ffffff',
      text: '#ffffff',
    },
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Defense',
    description: 'Titanium dark gray matrix with graphite cards, discrete security status indicators, and technical layout grid.',
    badge: 'SecOps Dark',
    bgClass: 'bg-[#121316]',
    canvasBg: '#121316',
    surfaceClass: 'bg-[#1a1b20] border border-neutral-700/60 text-neutral-100',
    textClass: 'text-neutral-100',
    subtextClass: 'text-neutral-400',
    borderClass: 'border-neutral-700',
    accentColor: '#e2e8f0',
    accentBadgeClass: 'bg-neutral-800 text-neutral-200 border border-neutral-700',
    fontFamily: 'font-mono',
    previewColors: {
      bg: '#121316',
      surface: '#1a1b20',
      accent: '#e2e8f0',
      text: '#f1f5f9',
    },
  },
  nordic: {
    id: 'nordic',
    name: 'Nordic Minimalist',
    description: 'Warm, refined light slate paper aesthetic with high typographic contrast, subtle rules, and clean presentation flow.',
    badge: 'Clean Editorial',
    bgClass: 'bg-[#f8fafc] text-neutral-900',
    canvasBg: '#f8fafc',
    surfaceClass: 'bg-white border border-neutral-300 text-neutral-900 shadow-sm',
    textClass: 'text-neutral-950',
    subtextClass: 'text-neutral-600',
    borderClass: 'border-neutral-300',
    accentColor: '#0f172a',
    accentBadgeClass: 'bg-neutral-900 text-white border border-neutral-900',
    fontFamily: 'font-sans',
    previewColors: {
      bg: '#f8fafc',
      surface: '#ffffff',
      accent: '#0f172a',
      text: '#09090b',
    },
  },
  frontier: {
    id: 'frontier',
    name: 'AI Frontier',
    description: 'Deep cosmic obsidian with subtle violet-slate borders, radiant code containers, and AI research presentation styling.',
    badge: 'AI Research',
    bgClass: 'bg-[#0a0c14]',
    canvasBg: '#0a0c14',
    surfaceClass: 'bg-[#121524] border border-indigo-950 text-neutral-100',
    textClass: 'text-white',
    subtextClass: 'text-neutral-400',
    borderClass: 'border-neutral-800',
    accentColor: '#e0e7ff',
    accentBadgeClass: 'bg-neutral-800 text-neutral-200 border border-neutral-700',
    fontFamily: 'font-sans',
    previewColors: {
      bg: '#0a0c14',
      surface: '#121524',
      accent: '#c7d2fe',
      text: '#f8fafc',
    },
  },
};

export const THEME_LIST = Object.values(TECH_THEMES);
