// Canonical R datasets for instant exploration and testing

export interface DatasetItem {
  name: string;
  filename: string;
  description: string;
  source: string;
  rows: number;
  cols: number;
  data: Record<string, any>[];
}

export const SAMPLE_DATASETS: DatasetItem[] = [
  {
    name: 'iris',
    filename: 'iris.csv',
    description: "Fisher's classic 1936 dataset measuring 4 morphological features across 3 Iris flower species.",
    source: 'R datasets package (datasets::iris)',
    rows: 150,
    cols: 5,
    data: [
      { sepal_length: 5.1, sepal_width: 3.5, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.9, sepal_width: 3.0, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.7, sepal_width: 3.2, petal_length: 1.3, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.6, sepal_width: 3.1, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.6, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.4, sepal_width: 3.9, petal_length: 1.7, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 4.6, sepal_width: 3.4, petal_length: 1.4, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.4, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.4, sepal_width: 2.9, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.9, sepal_width: 3.1, petal_length: 1.5, petal_width: 0.1, species: 'setosa' },
      { sepal_length: 5.4, sepal_width: 3.7, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.8, sepal_width: 3.4, petal_length: 1.6, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.8, sepal_width: 3.0, petal_length: 1.4, petal_width: 0.1, species: 'setosa' },
      { sepal_length: 4.3, sepal_width: 3.0, petal_length: 1.1, petal_width: 0.1, species: 'setosa' },
      { sepal_length: 5.8, sepal_width: 4.0, petal_length: 1.2, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.7, sepal_width: 4.4, petal_length: 1.5, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 5.4, sepal_width: 3.9, petal_length: 1.3, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.5, petal_length: 1.4, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 5.7, sepal_width: 3.8, petal_length: 1.7, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.8, petal_length: 1.5, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 5.4, sepal_width: 3.4, petal_length: 1.7, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.7, petal_length: 1.5, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 4.6, sepal_width: 3.6, petal_length: 1.0, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.3, petal_length: 1.7, petal_width: 0.5, species: 'setosa' },
      { sepal_length: 4.8, sepal_width: 3.4, petal_length: 1.9, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.0, petal_length: 1.6, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.4, petal_length: 1.6, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 5.2, sepal_width: 3.5, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.2, sepal_width: 3.4, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.7, sepal_width: 3.2, petal_length: 1.6, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.8, sepal_width: 3.1, petal_length: 1.6, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.4, sepal_width: 3.4, petal_length: 1.5, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 5.2, sepal_width: 4.1, petal_length: 1.5, petal_width: 0.1, species: 'setosa' },
      { sepal_length: 5.5, sepal_width: 4.2, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.9, sepal_width: 3.1, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.2, petal_length: 1.2, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.5, sepal_width: 3.5, petal_length: 1.3, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.9, sepal_width: 3.6, petal_length: 1.4, petal_width: 0.1, species: 'setosa' },
      { sepal_length: 4.4, sepal_width: 3.0, petal_length: 1.3, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.4, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.5, petal_length: 1.3, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 4.5, sepal_width: 2.3, petal_length: 1.3, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 4.4, sepal_width: 3.2, petal_length: 1.3, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.5, petal_length: 1.6, petal_width: 0.6, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.8, petal_length: 1.9, petal_width: 0.4, species: 'setosa' },
      { sepal_length: 4.8, sepal_width: 3.0, petal_length: 1.4, petal_width: 0.3, species: 'setosa' },
      { sepal_length: 5.1, sepal_width: 3.8, petal_length: 1.6, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 4.6, sepal_width: 3.2, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.3, sepal_width: 3.7, petal_length: 1.5, petal_width: 0.2, species: 'setosa' },
      { sepal_length: 5.0, sepal_width: 3.3, petal_length: 1.4, petal_width: 0.2, species: 'setosa' },
      // Versicolor
      { sepal_length: 7.0, sepal_width: 3.2, petal_length: 4.7, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 6.4, sepal_width: 3.2, petal_length: 4.5, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 6.9, sepal_width: 3.1, petal_length: 4.9, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 5.5, sepal_width: 2.3, petal_length: 4.0, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.5, sepal_width: 2.8, petal_length: 4.6, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 5.7, sepal_width: 2.8, petal_length: 4.5, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.3, sepal_width: 3.3, petal_length: 4.7, petal_width: 1.6, species: 'versicolor' },
      { sepal_length: 4.9, sepal_width: 2.4, petal_length: 3.3, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 6.6, sepal_width: 2.9, petal_length: 4.6, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.2, sepal_width: 2.7, petal_length: 3.9, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 5.0, sepal_width: 2.0, petal_length: 3.5, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 5.9, sepal_width: 3.0, petal_length: 4.2, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 6.0, sepal_width: 2.2, petal_length: 4.0, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 6.1, sepal_width: 2.9, petal_length: 4.7, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 5.6, sepal_width: 2.9, petal_length: 3.6, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.7, sepal_width: 3.1, petal_length: 4.4, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 5.6, sepal_width: 3.0, petal_length: 4.5, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 5.8, sepal_width: 2.7, petal_length: 4.1, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 6.2, sepal_width: 2.2, petal_length: 4.5, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 5.6, sepal_width: 2.5, petal_length: 3.9, petal_width: 1.1, species: 'versicolor' },
      { sepal_length: 5.9, sepal_width: 3.2, petal_length: 4.8, petal_width: 1.8, species: 'versicolor' },
      { sepal_length: 6.1, sepal_width: 2.8, petal_length: 4.0, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.3, sepal_width: 2.5, petal_length: 4.9, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 6.1, sepal_width: 2.8, petal_length: 4.7, petal_width: 1.2, species: 'versicolor' },
      { sepal_length: 6.4, sepal_width: 2.9, petal_length: 4.3, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.6, sepal_width: 3.0, petal_length: 4.4, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 6.8, sepal_width: 2.8, petal_length: 4.8, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 6.7, sepal_width: 3.0, petal_length: 5.0, petal_width: 1.7, species: 'versicolor' },
      { sepal_length: 6.0, sepal_width: 2.9, petal_length: 4.5, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 5.7, sepal_width: 2.6, petal_length: 3.5, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 5.5, sepal_width: 2.4, petal_length: 3.8, petal_width: 1.1, species: 'versicolor' },
      { sepal_length: 5.5, sepal_width: 2.4, petal_length: 3.7, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 5.8, sepal_width: 2.7, petal_length: 3.9, petal_width: 1.2, species: 'versicolor' },
      { sepal_length: 6.0, sepal_width: 2.7, petal_length: 5.1, petal_width: 1.6, species: 'versicolor' },
      { sepal_length: 5.4, sepal_width: 3.0, petal_length: 4.5, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 6.0, sepal_width: 3.4, petal_length: 4.5, petal_width: 1.6, species: 'versicolor' },
      { sepal_length: 6.7, sepal_width: 3.1, petal_length: 4.7, petal_width: 1.5, species: 'versicolor' },
      { sepal_length: 6.3, sepal_width: 2.3, petal_length: 4.4, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.6, sepal_width: 3.0, petal_length: 4.1, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.5, sepal_width: 2.5, petal_length: 4.0, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.5, sepal_width: 2.6, petal_length: 4.4, petal_width: 1.2, species: 'versicolor' },
      { sepal_length: 6.1, sepal_width: 3.0, petal_length: 4.6, petal_width: 1.4, species: 'versicolor' },
      { sepal_length: 5.8, sepal_width: 2.6, petal_length: 4.0, petal_width: 1.2, species: 'versicolor' },
      { sepal_length: 5.0, sepal_width: 2.3, petal_length: 3.3, petal_width: 1.0, species: 'versicolor' },
      { sepal_length: 5.6, sepal_width: 2.7, petal_length: 4.2, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.7, sepal_width: 3.0, petal_length: 4.2, petal_width: 1.2, species: 'versicolor' },
      { sepal_length: 5.7, sepal_width: 2.9, petal_length: 4.2, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 6.2, sepal_width: 2.9, petal_length: 4.3, petal_width: 1.3, species: 'versicolor' },
      { sepal_length: 5.1, sepal_width: 2.5, petal_length: 3.0, petal_width: 1.1, species: 'versicolor' },
      { sepal_length: 5.7, sepal_width: 2.8, petal_length: 4.1, petal_width: 1.3, species: 'versicolor' },
      // Virginica
      { sepal_length: 6.3, sepal_width: 3.3, petal_length: 6.0, petal_width: 2.5, species: 'virginica' },
      { sepal_length: 5.8, sepal_width: 2.7, petal_length: 5.1, petal_width: 1.9, species: 'virginica' },
      { sepal_length: 7.1, sepal_width: 3.0, petal_length: 5.9, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 6.3, sepal_width: 2.9, petal_length: 5.6, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.5, sepal_width: 3.0, petal_length: 5.8, petal_width: 2.2, species: 'virginica' },
      { sepal_length: 7.6, sepal_width: 3.0, petal_length: 6.6, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 4.9, sepal_width: 2.5, petal_length: 4.5, petal_width: 1.7, species: 'virginica' },
      { sepal_length: 7.3, sepal_width: 2.9, petal_length: 6.3, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.7, sepal_width: 2.5, petal_length: 5.8, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 7.2, sepal_width: 3.6, petal_length: 6.1, petal_width: 2.5, species: 'virginica' },
      { sepal_length: 6.5, sepal_width: 3.2, petal_length: 5.1, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 6.4, sepal_width: 2.7, petal_length: 5.3, petal_width: 1.9, species: 'virginica' },
      { sepal_length: 6.8, sepal_width: 3.0, petal_length: 5.5, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 5.7, sepal_width: 2.5, petal_length: 5.0, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 5.8, sepal_width: 2.8, petal_length: 5.1, petal_width: 2.4, species: 'virginica' },
      { sepal_length: 6.4, sepal_width: 3.2, petal_length: 5.3, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 6.5, sepal_width: 3.0, petal_length: 5.5, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 7.7, sepal_width: 3.8, petal_length: 6.7, petal_width: 2.2, species: 'virginica' },
      { sepal_length: 7.7, sepal_width: 2.6, petal_length: 6.9, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 6.0, sepal_width: 2.2, petal_length: 5.0, petal_width: 1.5, species: 'virginica' },
      { sepal_length: 6.9, sepal_width: 3.2, petal_length: 5.7, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 5.6, sepal_width: 2.8, petal_length: 4.9, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 7.7, sepal_width: 2.8, petal_length: 6.7, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 6.3, sepal_width: 2.7, petal_length: 4.9, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.7, sepal_width: 3.3, petal_length: 5.7, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 7.2, sepal_width: 3.2, petal_length: 6.0, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.2, sepal_width: 2.8, petal_length: 4.8, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.1, sepal_width: 3.0, petal_length: 4.9, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.4, sepal_width: 2.8, petal_length: 5.6, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 7.2, sepal_width: 3.0, petal_length: 5.8, petal_width: 1.6, species: 'virginica' },
      { sepal_length: 7.4, sepal_width: 2.8, petal_length: 6.1, petal_width: 1.9, species: 'virginica' },
      { sepal_length: 7.9, sepal_width: 3.8, petal_length: 6.4, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 6.4, sepal_width: 2.8, petal_length: 5.6, petal_width: 2.2, species: 'virginica' },
      { sepal_length: 6.3, sepal_width: 2.8, petal_length: 5.1, petal_width: 1.5, species: 'virginica' },
      { sepal_length: 6.1, sepal_width: 2.6, petal_length: 5.6, petal_width: 1.4, species: 'virginica' },
      { sepal_length: 7.7, sepal_width: 3.0, petal_length: 6.1, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 6.3, sepal_width: 3.4, petal_length: 5.6, petal_width: 2.4, species: 'virginica' },
      { sepal_length: 6.4, sepal_width: 3.1, petal_length: 5.5, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.0, sepal_width: 3.0, petal_length: 4.8, petal_width: 1.8, species: 'virginica' },
      { sepal_length: 6.9, sepal_width: 3.1, petal_length: 5.4, petal_width: 2.1, species: 'virginica' },
      { sepal_length: 6.7, sepal_width: 3.1, petal_length: 5.6, petal_width: 2.4, species: 'virginica' },
      { sepal_length: 6.9, sepal_width: 3.1, petal_length: 5.1, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 5.8, sepal_width: 2.7, petal_length: 5.1, petal_width: 1.9, species: 'virginica' },
      { sepal_length: 6.8, sepal_width: 3.2, petal_length: 5.9, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 6.7, sepal_width: 3.3, petal_length: 5.7, petal_width: 2.5, species: 'virginica' },
      { sepal_length: 6.7, sepal_width: 3.0, petal_length: 5.2, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 6.3, sepal_width: 2.5, petal_length: 5.0, petal_width: 1.9, species: 'virginica' },
      { sepal_length: 6.5, sepal_width: 3.0, petal_length: 5.2, petal_width: 2.0, species: 'virginica' },
      { sepal_length: 6.2, sepal_width: 3.4, petal_length: 5.4, petal_width: 2.3, species: 'virginica' },
      { sepal_length: 5.9, sepal_width: 3.0, petal_length: 5.1, petal_width: 1.8, species: 'virginica' }
    ]
  },
  {
    name: 'mtcars',
    filename: 'mtcars.csv',
    description: '1974 Motor Trend US magazine road tests on 32 automobiles (10 aspects of design and performance).',
    source: 'R datasets package (datasets::mtcars)',
    rows: 32,
    cols: 11,
    data: [
      { model: 'Mazda RX4', mpg: 21.0, cyl: 6, disp: 160.0, hp: 110, drat: 3.90, wt: 2.620, qsec: 16.46, vs: 0, am: 1, gear: 4, carb: 4 },
      { model: 'Mazda RX4 Wag', mpg: 21.0, cyl: 6, disp: 160.0, hp: 110, drat: 3.90, wt: 2.875, qsec: 17.02, vs: 0, am: 1, gear: 4, carb: 4 },
      { model: 'Datsun 710', mpg: 22.8, cyl: 4, disp: 108.0, hp: 93, drat: 3.85, wt: 2.320, qsec: 18.61, vs: 1, am: 1, gear: 4, carb: 1 },
      { model: 'Hornet 4 Drive', mpg: 21.4, cyl: 6, disp: 258.0, hp: 110, drat: 3.08, wt: 3.215, qsec: 19.44, vs: 1, am: 0, gear: 3, carb: 1 },
      { model: 'Hornet Sportabout', mpg: 18.7, cyl: 8, disp: 360.0, hp: 175, drat: 3.15, wt: 3.440, qsec: 17.02, vs: 0, am: 0, gear: 3, carb: 2 },
      { model: 'Valiant', mpg: 18.1, cyl: 6, disp: 225.0, hp: 105, drat: 2.76, wt: 3.460, qsec: 20.22, vs: 1, am: 0, gear: 3, carb: 1 },
      { model: 'Duster 360', mpg: 14.3, cyl: 8, disp: 360.0, hp: 245, drat: 3.21, wt: 3.570, qsec: 15.84, vs: 0, am: 0, gear: 3, carb: 4 },
      { model: 'Merc 240D', mpg: 24.4, cyl: 4, disp: 146.7, hp: 62, drat: 3.69, wt: 3.190, qsec: 20.00, vs: 1, am: 0, gear: 4, carb: 2 },
      { model: 'Merc 230', mpg: 22.8, cyl: 4, disp: 140.8, hp: 95, drat: 3.92, wt: 3.150, qsec: 22.90, vs: 1, am: 0, gear: 4, carb: 2 },
      { model: 'Merc 280', mpg: 19.2, cyl: 6, disp: 167.6, hp: 123, drat: 3.92, wt: 3.440, qsec: 18.30, vs: 1, am: 0, gear: 4, carb: 4 },
      { model: 'Merc 280C', mpg: 17.8, cyl: 6, disp: 167.6, hp: 123, drat: 3.92, wt: 3.440, qsec: 18.90, vs: 1, am: 0, gear: 4, carb: 4 },
      { model: 'Merc 450SE', mpg: 16.4, cyl: 8, disp: 275.8, hp: 180, drat: 3.07, wt: 4.070, qsec: 17.40, vs: 0, am: 0, gear: 3, carb: 3 },
      { model: 'Merc 450SL', mpg: 17.3, cyl: 8, disp: 275.8, hp: 180, drat: 3.07, wt: 3.730, qsec: 17.60, vs: 0, am: 0, gear: 3, carb: 3 },
      { model: 'Merc 450SLC', mpg: 15.2, cyl: 8, disp: 275.8, hp: 180, drat: 3.07, wt: 3.780, qsec: 18.00, vs: 0, am: 0, gear: 3, carb: 3 },
      { model: 'Cadillac Fleetwood', mpg: 10.4, cyl: 8, disp: 472.0, hp: 205, drat: 2.93, wt: 5.250, qsec: 17.98, vs: 0, am: 0, gear: 3, carb: 4 },
      { model: 'Lincoln Continental', mpg: 10.4, cyl: 8, disp: 460.0, hp: 215, drat: 3.00, wt: 5.424, qsec: 17.82, vs: 0, am: 0, gear: 3, carb: 4 },
      { model: 'Chrysler Imperial', mpg: 14.7, cyl: 8, disp: 440.0, hp: 230, drat: 3.23, wt: 5.345, qsec: 17.42, vs: 0, am: 0, gear: 3, carb: 4 },
      { model: 'Fiat 128', mpg: 32.4, cyl: 4, disp: 78.7, hp: 66, drat: 4.08, wt: 2.200, qsec: 19.47, vs: 1, am: 1, gear: 4, carb: 1 },
      { model: 'Honda Civic', mpg: 30.4, cyl: 4, disp: 75.7, hp: 52, drat: 4.93, wt: 1.615, qsec: 18.52, vs: 1, am: 1, gear: 4, carb: 2 },
      { model: 'Toyota Corolla', mpg: 33.9, cyl: 4, disp: 71.1, hp: 65, drat: 4.22, wt: 1.835, qsec: 19.90, vs: 1, am: 1, gear: 4, carb: 1 },
      { model: 'Toyota Corona', mpg: 21.5, cyl: 4, disp: 120.1, hp: 97, drat: 3.70, wt: 2.465, qsec: 20.01, vs: 1, am: 0, gear: 3, carb: 1 },
      { model: 'Dodge Challenger', mpg: 15.5, cyl: 8, disp: 318.0, hp: 150, drat: 2.76, wt: 3.520, qsec: 16.87, vs: 0, am: 0, gear: 3, carb: 2 },
      { model: 'AMC Javelin', mpg: 15.2, cyl: 8, disp: 304.0, hp: 150, drat: 3.15, wt: 3.435, qsec: 17.30, vs: 0, am: 0, gear: 3, carb: 2 },
      { model: 'Camaro Z28', mpg: 13.3, cyl: 8, disp: 350.0, hp: 245, drat: 3.73, wt: 3.840, qsec: 15.41, vs: 0, am: 0, gear: 3, carb: 4 },
      { model: 'Pontiac Firebird', mpg: 19.2, cyl: 8, disp: 400.0, hp: 175, drat: 3.08, wt: 3.845, qsec: 17.05, vs: 0, am: 0, gear: 3, carb: 2 },
      { model: 'Fiat X1-9', mpg: 27.3, cyl: 4, disp: 79.0, hp: 66, drat: 4.08, wt: 1.935, qsec: 18.90, vs: 1, am: 1, gear: 4, carb: 1 },
      { model: 'Porsche 914-2', mpg: 26.0, cyl: 4, disp: 120.3, hp: 91, drat: 4.43, wt: 2.140, qsec: 16.70, vs: 0, am: 1, gear: 5, carb: 2 },
      { model: 'Lotus Europa', mpg: 30.4, cyl: 4, disp: 95.1, hp: 113, drat: 3.77, wt: 1.513, qsec: 16.90, vs: 1, am: 1, gear: 5, carb: 2 },
      { model: 'Ford Pantera L', mpg: 15.8, cyl: 8, disp: 351.0, hp: 264, drat: 4.22, wt: 3.170, qsec: 14.50, vs: 0, am: 1, gear: 5, carb: 4 },
      { model: 'Ferrari Dino', mpg: 19.7, cyl: 6, disp: 145.0, hp: 175, drat: 3.62, wt: 2.770, qsec: 15.50, vs: 0, am: 1, gear: 5, carb: 6 },
      { model: 'Maserati Bora', mpg: 15.0, cyl: 8, disp: 301.0, hp: 335, drat: 3.54, wt: 3.570, qsec: 14.60, vs: 0, am: 1, gear: 5, carb: 8 },
      { model: 'Volvo 142E', mpg: 21.4, cyl: 4, disp: 121.0, hp: 109, drat: 4.11, wt: 2.780, qsec: 18.60, vs: 1, am: 1, gear: 4, carb: 2 }
    ]
  },
  {
    name: 'penguins',
    filename: 'penguins.csv',
    description: 'Palmer Archipelago (Antarctica) penguin size measurements for 3 species (Adelie, Chinstrap, Gentoo).',
    source: 'palmerpenguins package by Allison Horst',
    rows: 40,
    cols: 7,
    data: [
      { species: 'Adelie', island: 'Torgersen', bill_length_mm: 39.1, bill_depth_mm: 18.7, flipper_length_mm: 181, body_mass_g: 3750, sex: 'male' },
      { species: 'Adelie', island: 'Torgersen', bill_length_mm: 39.5, bill_depth_mm: 17.4, flipper_length_mm: 186, body_mass_g: 3800, sex: 'female' },
      { species: 'Adelie', island: 'Torgersen', bill_length_mm: 40.3, bill_depth_mm: 18.0, flipper_length_mm: 195, body_mass_g: 3250, sex: 'female' },
      { species: 'Adelie', island: 'Torgersen', bill_length_mm: 36.7, bill_depth_mm: 19.3, flipper_length_mm: 193, body_mass_g: 3450, sex: 'female' },
      { species: 'Adelie', island: 'Torgersen', bill_length_mm: 39.3, bill_depth_mm: 20.6, flipper_length_mm: 190, body_mass_g: 3650, sex: 'male' },
      { species: 'Adelie', island: 'Biscoe', bill_length_mm: 37.8, bill_depth_mm: 18.3, flipper_length_mm: 174, body_mass_g: 3400, sex: 'female' },
      { species: 'Adelie', island: 'Biscoe', bill_length_mm: 37.7, bill_depth_mm: 18.7, flipper_length_mm: 180, body_mass_g: 3600, sex: 'male' },
      { species: 'Adelie', island: 'Biscoe', bill_length_mm: 35.9, bill_depth_mm: 19.2, flipper_length_mm: 189, body_mass_g: 3800, sex: 'female' },
      { species: 'Adelie', island: 'Dream', bill_length_mm: 39.5, bill_depth_mm: 16.7, flipper_length_mm: 178, body_mass_g: 3250, sex: 'female' },
      { species: 'Adelie', island: 'Dream', bill_length_mm: 37.2, bill_depth_mm: 18.1, flipper_length_mm: 178, body_mass_g: 3900, sex: 'male' },
      { species: 'Adelie', island: 'Dream', bill_length_mm: 39.5, bill_depth_mm: 17.8, flipper_length_mm: 188, body_mass_g: 3300, sex: 'female' },
      { species: 'Adelie', island: 'Dream', bill_length_mm: 40.9, bill_depth_mm: 18.9, flipper_length_mm: 184, body_mass_g: 3900, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 46.1, bill_depth_mm: 13.2, flipper_length_mm: 211, body_mass_g: 4500, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 50.0, bill_depth_mm: 16.3, flipper_length_mm: 230, body_mass_g: 5700, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 48.7, bill_depth_mm: 14.1, flipper_length_mm: 210, body_mass_g: 4450, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 50.0, bill_depth_mm: 15.2, flipper_length_mm: 218, body_mass_g: 5700, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 47.6, bill_depth_mm: 14.5, flipper_length_mm: 215, body_mass_g: 5400, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 46.5, bill_depth_mm: 13.5, flipper_length_mm: 210, body_mass_g: 4550, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 45.4, bill_depth_mm: 14.6, flipper_length_mm: 211, body_mass_g: 4800, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 46.7, bill_depth_mm: 15.3, flipper_length_mm: 219, body_mass_g: 5200, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 43.3, bill_depth_mm: 13.4, flipper_length_mm: 209, body_mass_g: 4400, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 46.8, bill_depth_mm: 15.4, flipper_length_mm: 215, body_mass_g: 5150, sex: 'male' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 40.9, bill_depth_mm: 13.7, flipper_length_mm: 214, body_mass_g: 4650, sex: 'female' },
      { species: 'Gentoo', island: 'Biscoe', bill_length_mm: 49.0, bill_depth_mm: 16.1, flipper_length_mm: 216, body_mass_g: 5550, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 46.5, bill_depth_mm: 17.9, flipper_length_mm: 192, body_mass_g: 3500, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 50.0, bill_depth_mm: 19.5, flipper_length_mm: 196, body_mass_g: 3900, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 51.3, bill_depth_mm: 19.2, flipper_length_mm: 197, body_mass_g: 3650, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 45.4, bill_depth_mm: 18.7, flipper_length_mm: 188, body_mass_g: 3525, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 52.7, bill_depth_mm: 19.8, flipper_length_mm: 197, body_mass_g: 3725, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 45.2, bill_depth_mm: 17.8, flipper_length_mm: 198, body_mass_g: 3950, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 46.1, bill_depth_mm: 18.2, flipper_length_mm: 198, body_mass_g: 3800, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 51.3, bill_depth_mm: 18.2, flipper_length_mm: 197, body_mass_g: 3750, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 46.0, bill_depth_mm: 18.9, flipper_length_mm: 195, body_mass_g: 4150, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 51.3, bill_depth_mm: 19.9, flipper_length_mm: 198, body_mass_g: 3700, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 46.6, bill_depth_mm: 17.8, flipper_length_mm: 193, body_mass_g: 3800, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 51.7, bill_depth_mm: 20.3, flipper_length_mm: 194, body_mass_g: 3775, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 47.0, bill_depth_mm: 17.3, flipper_length_mm: 185, body_mass_g: 3700, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 52.0, bill_depth_mm: 18.1, flipper_length_mm: 201, body_mass_g: 4050, sex: 'male' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 45.9, bill_depth_mm: 17.1, flipper_length_mm: 190, body_mass_g: 3575, sex: 'female' },
      { species: 'Chinstrap', island: 'Dream', bill_length_mm: 50.5, bill_depth_mm: 18.4, flipper_length_mm: 200, body_mass_g: 3400, sex: 'female' }
    ]
  }
];
